# Generated by Django 5.2.12 on 2026-03-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(unique=True)),
                ("total_jobs_active", models.IntegerField(default=0)),
                ("total_applications", models.IntegerField(default=0)),
                ("new_applications_today", models.IntegerField(default=0)),
                ("total_candidates", models.IntegerField(default=0)),
                ("stage_breakdown", models.JSONField(default=dict)),
                ("screen_rate", models.FloatField(default=0)),
                ("interview_rate", models.FloatField(default=0)),
                ("offer_rate", models.FloatField(default=0)),
                ("hire_rate", models.FloatField(default=0)),
                ("ai_calls_today", models.IntegerField(default=0)),
                (
                    "ai_cost_today_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("RESUME_PARSE", "Resume Parse"),
                            ("CANDIDATE_SCORE", "Candidate Score"),
                            ("INTERVIEW_QUESTIONS", "Interview Questions"),
                            ("JOB_INSIGHTS", "Job Insights"),
                        ],
                        max_length=30,
                    ),
                ),
                ("triggered_by", models.CharField(max_length=255)),
                ("model", models.CharField(default="gpt-4o", max_length=50)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="candidates.application",
                    ),
                ),
                (
                    "related_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="analytics_a_action_7a8fca_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_a_created_5151f0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="analytics_a_status_be9726_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stage", models.CharField(blank=True, max_length=20)),
                ("to_stage", models.CharField(max_length=20)),
                ("moved_by_clerk_id", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_events",
                        to="candidates.application",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_events",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_events",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application"], name="analytics_p_applica_fae568_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_p_created_8e939f_idx"
                    ),
                    models.Index(
                        fields=["to_stage"], name="analytics_p_to_stag_69ea39_idx"
                    ),
                ],
            },
        ),
    ]
