# Generated by Django 5.2.12 on 2026-03-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clerk_user_id", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("BLACKLISTED", "Blacklisted"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["clerk_user_id"], name="candidates__clerk_u_94eb92_idx"
                    ),
                    models.Index(fields=["email"], name="candidates__email_188e48_idx"),
                    models.Index(
                        fields=["status"], name="candidates__status_0f124f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SCREENED", "Screened"),
                            ("INTERVIEW", "Interview"),
                            ("TECHNICAL", "Technical Assessment"),
                            ("OFFER", "Offer"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Application"),
                            ("LINKEDIN", "LinkedIn"),
                            ("REFERRAL", "Referral"),
                            ("INDEED", "Indeed"),
                            ("OTHER", "Other"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                ("recruiter_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_reason", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage_updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.FloatField()),
                ("skills_score", models.FloatField(blank=True, null=True)),
                ("experience_score", models.FloatField(blank=True, null=True)),
                ("education_score", models.FloatField(blank=True, null=True)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("strengths", models.JSONField(default=list)),
                ("gaps", models.JSONField(default=list)),
                ("ai_reasoning", models.TextField(blank=True)),
                ("recommendation", models.CharField(blank=True, max_length=20)),
                ("interview_questions", models.JSONField(default=list)),
                ("scored_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_version", models.CharField(default="gpt-4o", max_length=50)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="candidates.application",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_scores",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_key", models.CharField(max_length=500)),
                ("s3_url", models.URLField(max_length=1000)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("parsed_skills", models.JSONField(blank=True, default=list)),
                ("parsed_experience", models.JSONField(blank=True, default=list)),
                ("parsed_education", models.JSONField(blank=True, default=list)),
                ("parsed_summary", models.TextField(blank=True)),
                ("years_of_experience", models.FloatField(blank=True, null=True)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("parse_error", models.TextField(blank=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to="candidates.application",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["stage"], name="candidates__stage_5c22fb_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applied_at"], name="candidates__applied_93209b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["is_flagged"], name="candidates__is_flag_121357_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "job")},
        ),
        migrations.AddIndex(
            model_name="candidatescore",
            index=models.Index(
                fields=["overall_score"], name="candidates__overall_dd7b49_idx"
            ),
        ),
    ]
